global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']
  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:8082']
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']